# Generated by Django 3.1.2 on 2020-10-11 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionbox', '0002_auto_20201008_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
